version: '3'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:80
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:80"
    env_file:
      - .env